### ISSUE TITLE
The server encountered an error and could not complete your request

### ISSUE THREAD

**Issue by AmsellemJoseph** [answerdev/answer#144]
Hi,

I have a small question, I don't understand why, but since last week, when I want to install a session with docker-compose, I have this page displayed. 

![Screen Shot 2022-12-25 at 11 24 10](https://user-images.githubusercontent.com/79039145/209462955-1437ff01-4a73-46ac-8c34-5fae7b9eb111.png)

Yet usually everything works but I really don't see it, yet I use this script:

```
version: "3"
services:
  answer:
    image: answerdev/answer
    ports:
      - '172.17.0.1:9080:80'
    restart: always
    volumes:
      - answer-data:/data

volumes:
  answer-data:
```

Thank you in advance for your reply

**Comment by AmsellemJoseph** [comment]
in fact I install it in elest.io, my docker-compose is like that

```
version: "3.9"
services:
  answer:
    image: answerdev/answer:latest
    ports:
      - '172.17.0.1:9080:80'
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./answer-data/data:/data
  db:
    image: mariadb:10.4.7
    ports:
      - '172.17.0.1:13306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: answer
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      timeout: 20s
      retries: 10
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']
    volumes:
      - ./answer-data/mysql:/var/lib/mysql
```

and my elestio.yml is like that

```
ports:
  - protocol: "HTTPS"
    targetProtocol: "HTTP"
    listeningPort: "443"
    targetPort: "9988"
    targetIP: "172.17.0.1"
    public: true
    path: "/"
    isAuth: false
environments:
  - key: "DOMAIN"
    value: "[CI_CD_DOMAIN]"
  - key: ADMIN_PASSWORD
    value: "random_password"
  - key: "ADMIN_EMAIL"
    value: "[EMAIL]"
  - key: "ANYMAIL"
    value: "True"
  - key: "DEFAULT_FROM_EMAIL"
    value: "[DOMAIN]@vm.elestio.app"
  - key: "EMAIL_HOST"
    value: "172.17.0.1"
  - key: "EMAIL_PORT"
    value: "25"
  - key: "EMAIL_HOST_USER"
    value: ""
  - key: "EMAIL_HOST_PASSWORD"
    value: ""
  - key: "EMAIL_USE_TLS"
    value: "False"
  - key: "EMAIL_USE_SSL"
    value: "False"

config:
  runTime: "dockerCompose"
  version: ""
  framework: ""
  buildCommand: "docker-compose build"
  buildDir: "/"
  runCommand: "docker-compose up -d"
  icon: ""
  screenshot: "answer.jpg"
lifeCycleConfig:
  preInstallCommand: "./scripts/preInstall.sh"
  postInstallCommand: "./scripts/postInstall.sh"
  preBackupCommand: "./scripts/preBackup.sh"
  postBackupCommand: "./scripts/postBackup.sh"
  preRestoreCommand: "./scripts/preRestore.sh"
  postRestoreCommand: "./scripts/postRestore.sh"
webUI:
  - url: "https://[CI_CD_DOMAIN]"
    label: "Answer Admin"
    login: "[ADMIN_EMAIL]"
    password: "[ADMIN_PASSWORD]"
```

and since the last week everything was ok
