### ISSUE TITLE
Preserve site title when adding logo

### ISSUE THREAD

**Issue by HipyCas** [answerdev/answer#169]
**Is your feature request related to a problem? Please describe.**
I have added a logo to my site, action that hides the site title, while I would like to show both.

**Describe the solution you'd like**
An option in `Admin > Settings > Branding` to show the title of the site if a logo is provided.

**Comment by fenbox** [comment]
I think this is a bug. We will remove the deletion limit of the logo so that site title will display.

**Comment by HipyCas** [comment]
> I think this is a bug. We will remove the deletion limit of the logo so that site title will display.

Perfect, thanks a lot!

> If you want show both, it would be more appropriate to include text in the logo file.

I believe otherwise. Having the title separated from the logo allows the title to follow the same font as the rest of the site, change font size easier and sync the title throughout the whole site, any change regarding this will force you to change the logo which I believe is highly impractical.

**Comment by frafra** [comment]
Sorry, but I am using 1.2.5rc2 and I still see the issue.

This is my current workaround:
```css
.navbar-brand {
  display: flex;
  align-items: center;
}
.navbar-brand:after {
  padding-left: 1rem;
  content: "Site title";
}
```
