### ISSUE TITLE
数据库连接超时

### ISSUE THREAD

**Issue by abigmiu** [answerdev/answer#178]
![image](https://user-images.githubusercontent.com/43983920/213451834-75f11cbd-79e7-4b66-8604-b635c93650f2.png)

步骤
1：创建docker-compose 文件
```yaml
version: "3"
services:
  answer:
    image: answerdev/answer
    ports:
      - '9080:80'
    restart: on-failure
    volumes:
      - answer-data:/data

volumes:
  answer-data:
```
执行命令
```shell
docker-compose pull
docker-compose down
docker-compose up -d
```

连接宿主机 mysql
```shell

mysql > GRANT ALL PRIVILEGES ON answer.* TO 'answer'@'%' IDENTIFIED BY '密码' WITH GRANT OPTION;
mysql > flush privileges;

```

打开网站。 执行程序安装。 连接数据库的时候network 显示请求超时
