### ISSUE TITLE
IE load main page will always loading and show js error

### ISSUE THREAD

**Issue by Dev-Wiki** [answerdev/answer#280]
version: lastest

```yml
version: '3'

services:
  answer:
    image: answerdev/answer:latest
    restart: always
    ports:
      - '9082:80'
    volumes:
      - ./data:/data
```

![image](https://user-images.githubusercontent.com/12946956/227408646-0ff891d2-6db7-4f25-b1ca-44608eaba4bc.png)
