### ISSUE TITLE
a problem about website address in confirm url 

### ISSUE THREAD

**Issue by notfresh** [answerdev/answer#85]
I just run my local demo and register a none-admin user, the address in confirm url should not be 127.0.0.1, but my own domain name, how to config it?

Welcome to answer

Click the following link to confirm and activate your new account:
http://127.0.0.1:9080/users/account-activation?code=af6e98e5-59e1-480c-a6c3-ebedff76d200

If the above link is not clickable, try copying and pasting it into the address bar of your web browser.

**Comment by notfresh** [comment]
Oh, I update the configs/config.yaml

```
i18n:
  bundle_dir: "/data/i18n"
swaggerui:
  show: true
  protocol: http
  host: MyDMAIN
  address: ':80'
service_config:
  secret_key: "answer"
  web_host: "http://MyDMAIN:9080" # my own 
  upload_path: "/data/upfiles"
```
and use docker-compse restart, it's not working, so should I rebuild the image  or do something else?
