### ISSUE TITLE
Update initial data

### ISSUE THREAD

**Issue by fenbox** [answerdev/answer#909]
## Current

All data is empty and requires further configuration by the administrator to use.

## Expected

Have initial data such as tags, sample Q&A, etc., so users can start using it right away.

After the user fills in the admin account during installation and clicks the <kbd>Next</kbd> button, the following initial data will be generated automatically.

<img width="353" alt="image" src="https://github.com/apache/incubator-answer/assets/360618/3f8c9049-9504-4032-a1e4-00e21d0933f7">

Initial tag:

```
- name: support
  description: For general support questions.
```

Initial post:

```
- title: What is a tag?
  body: When asking a question, we need to choose tags. What are tags and why should I use them?
  tags:
    - support
  answer: Tags help to organize content and make searching easier. It helps your question get more attention from people interested in that tag. Tags also send notifications. If you are interested in some topic, follow that tag to get updates.

- title: What is reputation and how do I earn them?
  body: I see that each user has reputation points, What is it and how do I earn them?
  tags:
    - support
  answer: Your reputation points show how much the community values your knowledge. You earn points when someone find your question or answer helpful. You also get points when the person who asked the question thinks you did a good job and accepts your answer.
```

The author is the initial administrator.
